### ISSUE TITLE
README lacks instructions on how to install and enable this module

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/cwp-pdfexport#5]
The README.md file in its current state is a bit sparse. There are detailed instructions on installing and enabling the functionality of this module on https://github.com/silverstripe/cwp/blob/master/docs/en/02_Features/pdf_export.md 

I suggest we copy this information into the README.md or link to the CWP documentation under the installation heading.

**Comment by robbieaverill** [comment]
+1 for linking to the document over copying and pasting it. You could add a sentence like "If you're using the starter or Wātea theme, ensure you uncomment the PDF export button in PageUtilities.ss" for example, but I don't think we'd need to add much more

**Comment by raissanorth** [comment]
Also, there is a current issue https://github.com/silverstripe/silverstripe-framework/issues/7970 that may affect the configuration of this module. Depending on how we decide to resolve it, we should keep in mind to record necessary 'workarounds' in the documentation, if necessary. 

At the moment I changed my configuration to deal with this as follows:
```
---
Name: myconfig
---
CWP\PDFExport\Extensions\PDFExportExtension:
  pdf_export: true
```

**Comment by robbieaverill** [comment]
>Also, there is a current issue silverstripe/silverstripe-framework#7970 that may affect the configuration of this module

This has been resolved now in CWP 2.1.0

**Comment by dhensby** [comment]
soooooo is this done?

**Comment by robbieaverill** [comment]
I think we ended up with two issues in one here, but the original "update the readme" still needs to be done =)
