### ISSUE TITLE
PDF is not readable enough

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/cwp-pdfexport#6]
The PDF that is created is almost unreadable due to a very small font size and because the site's landscape format is being rendered as a portrait PDF. 

See the screenshot below:

<kbd>![image](https://user-images.githubusercontent.com/14869519/38479987-e660a4d2-3c16-11e8-9ea8-14536eeb78df.png)</kbd>

**Comment by robbieaverill** [comment]
Closing as #wontfix - the fix here is not to use this module, but use browser's print to PDF functionality instead
